#!/usr/bin/env python3
"""
Write **valid minimal .xlsx** files under `amcs/kotak-mahindra-mutual-fund/<YYYY-MM>/`.

These are **not** Kotak’s official disclosures — Radware blocks unattended fetch from this agent.
They exist so pipelines (parsers, DAGs, tests) have real Excel blobs to run against until you
replace them with files from a browser session (`fetch_kotak_playwright.py` or manual download).

  pip install -r scripts/requirements-kotak-stub.txt
  python3 scripts/seed_kotak_placeholders.py --months 2026-01 2026-02
"""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


def main() -> None:
    try:
        from openpyxl import Workbook
    except ImportError as e:
        raise SystemExit(
            "Need openpyxl: pip install -r scripts/requirements-kotak-stub.txt\n" f"{e}"
        ) from e

    parser = argparse.ArgumentParser(description="Seed Kotak placeholder xlsx files")
    parser.add_argument("--months", nargs="+", default=["2026-01", "2026-02"])
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing placeholder files of the same name",
    )
    args = parser.parse_args()

    amc = args.root / "amcs" / "kotak-mahindra-mutual-fund"

    for mk in args.months:
        datetime.strptime(mk, "%Y-%m")
        out_dir = amc / mk
        out_dir.mkdir(parents=True, exist_ok=True)
        fname = f"KOTAK_PLACEHOLDER_MONTHLY_PORTFOLIO_{mk}.xlsx"
        fpath = out_dir / fname

        if fpath.exists() and not args.force:
            print(f"Skip existing {fpath} (use --force)", flush=True)
            continue

        wb = Workbook()
        ws = wb.active
        ws.title = "Placeholder"
        ws["A1"] = (
            "STUB FILE — Replace with official Kotak monthly portfolio disclosure .xlsx. "
            "Automated fetch is blocked by Radware without your browser session."
        )
        ws["A3"] = "ISIN"
        ws["B3"] = "Name of Instrument"
        ws["C3"] = "% to Net Assets"
        ws["A4"] = "EXAMPLE001"
        ws["B4"] = "Example Security"
        ws["C4"] = "0.00"
        wb.save(fpath)

        body = fpath.read_bytes()
        h = hashlib.sha256(body).hexdigest()
        manifest = [
            {
                "month": mk,
                "download_url": "",
                "saved_as": fname,
                "label": "seed_kotak_placeholders.py (stub — not from Kotak site)",
                "sha256": h,
                "stub": True,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            }
        ]
        (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        print(f"Wrote {fpath} ({len(body)} bytes)", flush=True)

    note = amc / "PLACEHOLDERS.md"
    note.write_text(
        "# Placeholder workbooks\n\n"
        "The `.xlsx` files named `KOTAK_PLACEHOLDER_*.xlsx` were generated by "
        "`scripts/seed_kotak_placeholders.py`.\n\n"
        "**Replace them** with real monthly portfolio files from "
        "[Kotak forms & downloads](https://www.kotakmf.com/Information/forms-and-downloads) "
        "using `scripts/fetch_kotak_playwright.py` or manual download.\n",
        encoding="utf-8",
    )
    print(f"Wrote {note}", flush=True)


if __name__ == "__main__":
    main()
